const terrainDataKeys = <String>[
  'gen_qcFlag',
  'gen_idEnqueteur',
  'gen_idObservation',
  'gen_date',
  'gen_heure',
  'gen_pays',
  'gen_region',
  'gen_portPeche',
  'gen_zone',
  'gen_longitude',
  'gen_latitude',
  'suivi_typeObservation',
  'suivi_typeEnginCode',
  'suivi_typeEnginAutre',
  'suivi_typeEngin',
  'suivi_nbPieces',
  'suivi_idNavire',
  'suivi_idNasse',
  'suivi_debut',
  'suivi_fin',
  'suivi_chalut_type',
  'suivi_chalut_longueurRalingueInf',
  'suivi_chalut_ouvertureVerticale',
  'suivi_chalut_ouvertureHorizontale',
  'suivi_chalut_mailleCul',
  'suivi_mofi_longueur',
  'suivi_mofi_hauteur',
  'suivi_mofi_maille',
  'suivi_mofi_nbPiecesArmement',
  'suivi_mofi_nbArmements',
  'suivi_mofi_typeFiletDroit',
  'suivi_comb_longueur',
  'suivi_comb_hauteur',
  'suivi_comb_mailleCentrale',
  'suivi_comb_mailleExterieure',
  'suivi_comb_nbPiecesArmement',
  'suivi_comb_nbArmements',
  'suivi_comb_typeFiletDroit',
  'suivi_tr_longueur',
  'suivi_tr_hauteur',
  'suivi_tr_mailleCentrale',
  'suivi_tr_mailleExterieure',
  'suivi_tr_nbPiecesArmement',
  'suivi_tr_nbArmements',
  'suivi_tr_typeFiletDroit',
  'suivi_fenc_longueur',
  'suivi_fenc_hauteurChute',
  'suivi_fenc_mailleAile',
  'suivi_fenc_maillePoche',
  'suivi_fenc_typeFiletTournant',
  'suivi_nc_diametre',
  'suivi_nc_hauteur',
  'suivi_nc_ouverture',
  'suivi_nc_maille',
  'suivi_nc_nbre',
  'suivi_nc_typeNasses',
  'suivi_p_diametre',
  'suivi_p_nbre',
  'suivi_p_typePieges',
  'cap_nomCommun',
  'cap_espece',
  'cap_abondance',
  'cap_poidsTotal',
  'env_substrat',
  'env_profondeur',
  'env_temperature',
  'env_oxygene',
  'env_salinite',
  'rem_pecheurReticent',
  'rem_infoPartielle',
  'rem_gpsEstime',
  'rem_text',
];

const labDataKeys = <String>[
  'idObservation',
  'dateReception',
  'idLaboratoire',
  'idAnalyste',
  'dateAnalyse',
  'qcFlag',
  'espece',
  'idIndividu',
  'sexe',
  'stade',
  'maturite',
  'cw',
  'cl',
  'epaisseurC',
  'poidsTotal',
  'poidsEviscere',
  'appendicesGauche',
  'appendicesDroit',
  'pincesManquantes',
  'couleurOeufs',
  'poidsGonades',
  'poidsOeufs',
  'poidsEstomac',
  'indiceGonado',
  'poidsSpermatheque',
  'stadeMue',
  'tauxProteines',
  'tauxLipides',
  'tauxProteines2',
  'humidite',
  'cendres',
  'epibiontesOuiNon',
  'epibiontesDescription',
  'epibiontesType',
  'epibiontesEspeces',
  'remarques',
];

const lekDataKeys = <String>[
"Numéro de l'interview",
"nom de l'enquêteur",
'Date',
'pays',
'region',
'portPeche',
'portPecheAutre',
'Zone',
'Type Pêche',
'Nom ou code du pêcheur (facultatif)',
'Age',
'genre',
'Experience (Depuis quand)',
'Propriétaire/Locataire',
'Role (Capitaine/Marin)',
'Niveau éducation',
'Affiliation CNSS',
'Pêche activité principale',
'Pêche activité principale Autre',
'Zone de pêche',
'barque_matricule',
'barque_Longueur',
'barque_puissance',
"barque_Année d'achat (coque)",
'activité_Senne tournante coulissante: PS',
'activité_Chaluts :CH(Crevettier, Mediterranien, GOV, pélagique)',
'activité_Filets tournants : FT',
'activité_Trémails et maillants combinés: TMC',
'activité_Filets maillants dérivants: MD',
'activité_Filets maillants encerclants: MEC',
'activité_Trémails: TR(poisson, Crevettes, Seiche)',
'activité_Filets monofilament: MoFi',
'activité_Nasses (casiers): NC',
'activité_Pièges ( gargoulettes, Verveux...):P',
'activité_autre',
// --- BLOC EN-TÊTE ---
'Durée moyenne d’une marée',
'Nombre de sorties en mer en 2025',
'Nombre de sorties en mer_Janvier',
'Nombre de sorties en mer_Février',
'Nombre de sorties en mer_Mars',
'Nombre de sorties en mer_Avril',
'Nombre de sorties en mer_Mai',
'Nombre de sorties en mer_Juin',
'Nombre de sorties en mer_Juillet',
'Nombre de sorties en mer_Août',
'Nombre de sorties en mer_Septembre',
'Nombre de sorties en mer_Octobre',
'Nombre de sorties en mer_Novembre',
'Nombre de sorties en mer_Décembre',

//// --- CARACTÉRISTIQUES DE LA BARQUE ---
"caractéristique de l'engin_Filets_Filets droits (maillant, trémails, ….)_Longueur",
"caractéristique de l'engin_Filets_Filets droits (maillant, trémails, ….)_longueur",
"caractéristique de l'engin_Filets_Filets droits (maillant, trémails, ….)_Hauteur",
"caractéristique de l'engin_Filets_Filets droits (maillant, trémails, ….)_Maille/Maille centrale",
"caractéristique de l'engin_Filets_Filets droits (maillant, trémails, ….)_Maille extérieure",
"caractéristique de l'engin_Filets_Filets droits (maillant, trémails, ….)_Nbre de piéces par armement",
"caractéristique de l'engin_Filets_Filets droits (maillant, trémails, ….)_Nbre armements",

"caractéristique de l'engin_Filets_Filets Tournants_longueur",
"caractéristique de l'engin_Filets_Filets Tournants_Hauteur (chute)",
"caractéristique de l'engin_Filets_Filets Tournants_Maille aile",
"caractéristique de l'engin_Filets_Filets Tournants_Maille poche",

"caractéristique de l'engin_Filets_Pièges (gargoulette, pierre….)_Diamétre",
"caractéristique de l'engin_Filets_Pièges (gargoulette, pierre….)_Nbre",

"caractéristique de l'engin_Filets_Nasses_Diamétre",
"caractéristique de l'engin_Filets_Nasses_Hauteur",
"caractéristique de l'engin_Filets_Nasses_Ouverture",
"caractéristique de l'engin_Filets_Nasses_Maille",
"caractéristique de l'engin_Filets_Nasses_Nbre",

"caractéristique de l'engin_Filets_Chalut_Longueur ralingue inférieure",
"caractéristique de l'engin_Filets_Chalut_ouverture Verticale",
"caractéristique de l'engin_Filets_Chalut_ouverture horizentale",
"caractéristique de l'engin_Filets_Chalut_Maille de cul de chalut",
"caractéristique de l'engin_Filets_Chalut_Type de chalut",

"dynamique du crabe (photos des deux espéces)_Distinction entre les 2 espèces",

"dynamique du crabe (photos des deux espéces)_C. Sapidus_Année 1ére observation",
"dynamique du crabe (photos des deux espéces)_C. Sapidus_Environment (T°, S%., saison..)",
"dynamique du crabe (photos des deux espéces)_C. Sapidus_Distribution à l'apparition",
"dynamique du crabe (photos des deux espéces)_C. Sapidus_Distribution actuelle",
"dynamique du crabe (photos des deux espéces)_C. Sapidus_Profondeur",
"dynamique du crabe (photos des deux espéces)_C. Sapidus_Type de fond",
"dynamique du crabe (photos des deux espéces)_C. Sapidus_Zones sensibles à proximité",
"dynamique du crabe (photos des deux espéces)_C. Sapidus_Abondance depuis les 5 dernières années",
"dynamique du crabe (photos des deux espéces)_C. Sapidus_Saison de plus forte abondance",
"dynamique du crabe (photos des deux espéces)_C. Sapidus_Saison de reproduction",
"dynamique du crabe (photos des deux espéces)_C. Sapidus_Présence de juvéniles",
"dynamique du crabe (photos des deux espéces)_C. Sapidus_Taille moyenne observée",
"dynamique du crabe (photos des deux espéces)_C. Sapidus_Evolution des quantités capturées de crabe durant les 5 dernières années",
"dynamique du crabe (photos des deux espéces)_C. Sapidus_Evolution des quantités capturées de crabe durant les 5 dernières années_Tendance",
"dynamique du crabe (photos des deux espéces)_C. Sapidus_Evolution des quantités capturées de crabe durant les 5 dernières années_Zone la plus affectée",

"dynamique du crabe (photos des deux espéces)_P. segnis_Année 1ére observation",
"dynamique du crabe (photos des deux espéces)_P. segnis_Environment  (T°, S%, saison..)",
"dynamique du crabe (photos des deux espéces)_P. segnis_Distribution à l'apparition",
"dynamique du crabe (photos des deux espéces)_P. segnis_Distribution actuelle",
"dynamique du crabe (photos des deux espéces)_P. segnis_Profondeur",
"dynamique du crabe (photos des deux espéces)_P. segnis_Type de fond",
"dynamique du crabe (photos des deux espéces)_P. segnis_Zones sensibles à proximité",
"dynamique du crabe (photos des deux espéces)_P. segnis_Abondance depuis les 5 dernières années",
"dynamique du crabe (photos des deux espéces)_P. segnis_Saison de plus forte abondance",
"dynamique du crabe (photos des deux espéces)_P. segnis_Saison de reproduction",
"dynamique du crabe (photos des deux espéces)_P. segnis_Présence de juvéniles",
"dynamique du crabe (photos des deux espéces)_P. segnis_Taille moyenne observée",

"dynamique du crabe (photos des deux espéces)_P. segnis_Evolution des quantités capturées de crabe durant les 5 dernières années_Tendance",
"dynamique du crabe (photos des deux espéces)_P. segnis_Evolution des quantités capturées de crabe durant les 5 dernières années_Zone la plus affectée",

"dynamique du crabe (photos des deux espéces)_Les 2 espèces conf_Année 1ére observation",
"dynamique du crabe (photos des deux espéces)_Les 2 espèces conf_Environment  (T°, S%...)",
"dynamique du crabe (photos des deux espéces)_Les 2 espèces conf_Distribution à l'apparition",
"dynamique du crabe (photos des deux espéces)_Les 2 espèces conf_Distribution actuelle",
"dynamique du crabe (photos des deux espéces)_Les 2 espèces conf_Profondeur",
"dynamique du crabe (photos des deux espéces)_Les 2 espèces conf_Type de fond",
"dynamique du crabe (photos des deux espéces)_Les 2 espèces conf_Zones sensibles à proximité",
"dynamique du crabe (photos des deux espéces)_Les 2 espèces conf_Abondance depuis les 5 dernières années",
"dynamique du crabe (photos des deux espéces)_Les 2 espèces conf_Saison de plus forte abondance",
"dynamique du crabe (photos des deux espéces)_Les 2 espèces conf_Saison de reproduction",
"dynamique du crabe (photos des deux espéces)_Les 2 espèces conf_Présence de juvéniles",
"dynamique du crabe (photos des deux espéces)_Les 2 espèces conf_Taille moyenne observée",

"dynamique du crabe (photos des deux espéces)_Les 2 espèces conf_Evolution des quantités capturées de crabe durant les 5 dernières années_Tendance",
"dynamique du crabe (photos des deux espéces)_Les 2 espèces conf_Evolution des quantités capturées de crabe durant les 5 dernières années_Zone la plus affectée",

"impact écologique_impact sur  les habitats_Détail des changements_Herbiers disparaissent",
"impact écologique_impact sur  les habitats_Détail des changements_fond se creuse",
"impact écologique_impact sur  les habitats_Détail des changements_retourne le fond",
"impact écologique_impact sur  les habitats_Détail des changements_autre (à préciser)",

"impact écologique_Impact sur la  biodiversité_Détail des changements_Tendance",
"impact écologique_Impact sur la  biodiversité_Détail des changements_Depuis quand",
"impact écologique_Impact sur la  biodiversité_Détail des changements_Zone la plus affectée",
"impact écologique_Impact sur la  biodiversité_Détail des changements_Espèces les plus affectées",
"impact écologique_Impact sur la  biodiversité_Détail des changements_Espèce1",
"impact écologique_Impact sur la  biodiversité_Détail des changements_Espèce2",
"impact écologique_Impact sur la  biodiversité_Détail des changements_Espèce3",

"impact sur la pêche_Dégâts sur les engins",
"impact sur la pêche_engin le plus impacté",
"impact sur la pêche_Dégâts physique sur le pêcheur",
"impact sur la pêche_augmentation de la charge de travail",
"impact sur la pêche_Dégâts physique sur les captures",

"impact sur la pêche_Evolutions des captures totales_Tendance",
"impact sur la pêche_Evolutions des captures totales_Depuis quand",
"impact sur la pêche_Evolutions des captures totales_Espèces dominantes",
"impact sur la pêche_Evolutions des captures totales_Espèce1",
"impact sur la pêche_Evolutions des captures totales_Espèce2",
"impact sur la pêche_Evolutions des captures totales_Espèce3",

"Evolution de la catégorie de taille des espèces capturés_Tendance",
"Evolution de la catégorie de taille des espèces capturés_Depuis quand",
"Evolution de la catégorie de taille des espèces capturés_Nom de la zone la plus affectée",
"Evolution de la catégorie de taille des espèces capturés_Espèces les plus affectées",
"Evolution de la catégorie de taille des espèces capturés_Espèce1",
"Evolution de la catégorie de taille des espèces capturés_Espèce2",
"Evolution de la catégorie de taille des espèces capturés_Espèce3",

"Impact sur la rentabilité du pêcheur durant les cinq dernières années_Acceptation du crabe pour la commercialisation",
"Impact sur la rentabilité du pêcheur durant les cinq dernières années_Tendance de la valeur",

"Impact sur la rentabilité du pêcheur durant les cinq dernières années_Prix de vente actuel_prix vente consommateur",
"Impact sur la rentabilité du pêcheur durant les cinq dernières années_Prix de vente actuel_prix industrie",
"Impact sur la rentabilité du pêcheur durant les cinq dernières années_Prix de vente actuel_prix intermédiaire (mareyeurs)",
"Impact sur la rentabilité du pêcheur durant les cinq dernières années_Prix de vente actuel_Tendance de votre rentabilté",
"Impact sur la rentabilité du pêcheur durant les cinq dernières années_Prix de vente actuel_Tendance chiffre d'affaire",
"Impact sur la rentabilité du pêcheur durant les cinq dernières années_Prix de vente actuel_% variation chiffre affaire",
"Impact sur la rentabilité du pêcheur durant les cinq dernières années_Prix de vente actuel_Tendance des dépenses",
"Impact sur la rentabilité du pêcheur durant les cinq dernières années_Prix de vente actuel_% variations des dépenses",

"Adaptation locale_Modification des pratiques de pêche",

"Adaptation locale_Types d’adaptations (plusieurs possibles)_Modification engins",
"Adaptation locale_Types d’adaptations (plusieurs possibles)_Type de modification engins",
"Adaptation locale_Types d’adaptations (plusieurs possibles)_Engins mis hors d'usage",
"Adaptation locale_Types d’adaptations (plusieurs possibles)_Nouveaux engins",
"Adaptation locale_Types d’adaptations (plusieurs possibles)_Changement de zone",

"Adaptation locale_Changement du calendrier de pêche_Espèces cibles",
"Adaptation locale_Changement du calendrier de pêche_saison de pêche",
"Adaptation locale_Changement du calendrier de pêche_autres à préciser",
"Adaptation locale_Efficacité des adaptations",

"Etat des lieux_Perception de crabe",
"Etat des lieux_Etat de la gestion du crabe",
"Etat des lieux_Interêt dans l'implication de la gestion de CB",
"Etat des lieux_Affiliation GDAP SMSA ou association",
"Etat des lieux_Reglementation adéquate",
"Etat des lieux_Mesures de gestion proposées",
"Etat des lieux_Blooms, anomalies, mortalités",
"Etat des lieux_Pollutions",
"Etat des lieux_Etat du milieu (eaux)",
"Etat des lieux_Etat du Fond",
"Etat des lieux_Problèmes concernant la commercialisation",
"Etat des lieux_Principal problème rencontré",
"Etat des lieux_Suggestion d'améliration de l'activité",
"Niveau de confiance_niveau de confiance",
];